# Generated by Django 3.0.5 on 2020-06-08 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Пример',
                'verbose_name_plural': 'Примеры',
                'ordering': ['example'],
            },
        ),
        migrations.CreateModel(
            name='Tatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(unique=True, verbose_name='Татарское слово')),
                ('hit', models.BigIntegerField(default=0, verbose_name='Кол-во подборов')),
            ],
            options={
                'verbose_name': 'Слово на татарском',
                'verbose_name_plural': 'Слова на татарском',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField(blank=True, null=True, verbose_name='Перевод')),
                ('tatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translations', to='core.Tatar', verbose_name='Татарское слово')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
                'ordering': ['translation'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(verbose_name='Введенное слово')),
                ('hit_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Введено')),
                ('tatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.Tatar', verbose_name='Татарское слово')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История',
                'ordering': ['-hit_timestamp'],
            },
        ),
    ]
