# Generated by Django 3.0.7 on 2020-07-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200709_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['sent_timestamp'], 'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
    ]
