# Generated by Django 3.0.7 on 2020-07-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200710_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examples',
            new_name='Example',
        ),
        migrations.RenameModel(
            old_name='Translations',
            new_name='Translation',
        ),
    ]
