# Generated by Django 3.0.7 on 2020-09-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200710_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='trans',
            new_name='translation',
        ),
    ]
